spring:
    application:
        name: snaplab-gateway

    cloud:
        config:
            discovery:
                enabled: true
                service-id: config-service

server:
    port: 9100



